### ISSUE TITLE
Does Not Seem To Work With Hearthstone 6.1.3.14830 (EndOfStreamException)

### ISSUE THREAD

**Issue by chrislewisdev** [andburn/hs-art-extractor#4]
When attempting to run hs-art-extractor on my Hearthstone 6.1.3.14830 install, it encounters an EndOfStreamException while reading cardtextures0.unity3d.

This seems to be a result of the preSize variable (in AssetBundle.cs lines 30 - 35) receiving a value of 1634625894, which is much larger than the stream's length (which is 156032 from what I can see).

Perhaps the asset bundle file format changed with a recent update?

Exception Detail:
`System.IO.EndOfStreamException was unhandled
  HResult=-2147024858
  Message=Unable to read beyond the end of the stream.
  Source=mscorlib
  StackTrace:
       at System.IO.MemoryStream.InternalReadInt32()
       at System.IO.BinaryReader.ReadInt32()
       at HsArtExtractor.Util.BinaryBlock.ReadInt() in D:\Resources\hs-art-extractor\HsArtExtractor\Util\BinaryBlock.cs:line 75
       at HsArtExtractor.Unity.Objects.AssetBundle..ctor(BinaryBlock b) in D:\Resources\hs-art-extractor\HsArtExtractor\Unity\Objects\AssetBundle.cs:line 34
       at HsArtExtractor.Hearthstone.CardArtExtractor.LoadTextureInfo(List1 textureFiles) in D:\Resources\hs-art-extractor\HsArtExtractor\Hearthstone\CardArtExtractor.cs:line 168
       at HsArtExtractor.Hearthstone.CardArtExtractor.Extract(CardArtExtractorOptions opts) in D:\Resources\hs-art-extractor\HsArtExtractor\Hearthstone\CardArtExtractor.cs:line 97
       at HsArtExtractor.Extract.CardArt(CardArtExtractorOptions options) in D:\Resources\hs-art-extractor\HsArtExtractor\Extract.cs:line 28
       at HsArtExtractorCLI.Program.CardArtCommand(CardArtOptions opts) in D:\Resources\hs-art-extractor\HsArtExtractorCLI\Program.cs:line 90
       at HsArtExtractorCLI.Program.<>c.<Main>b__0_1(CardArtOptions opts) in D:\Resources\hs-art-extractor\HsArtExtractorCLI\Program.cs:line 21
       at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,TResult](ParserResult1 result, Func2 parsedFunc1, Func2 parsedFunc2, Func2 parsedFunc3, Func2 notParsedFunc)
       at HsArtExtractorCLI.Program.Main(String[] args) in D:\Resources\hs-art-extractor\HsArtExtractorCLI\Program.cs:line 18
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
`

**Comment by andburn** [comment]
Hi, thanks. I'll check this out soon.

**Comment by chrislewisdev** [comment]
Thanks for the quick turnaround, works nicely now :)
