### ISSUE TITLE
Hearthstone version 8.0 extract fail

### ISSUE THREAD

**Issue by mjschutz** [andburn/hs-art-extractor#8]
Hi.

Today I tested the extractor with new updated Hearthstone and it fails, the info is bellow:

Hearthstone Dir: C:\Program Files (x86)\Hearthstone
Saving to: .

Unhandled Exception: System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)

   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPath
Length, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   at System.IO.FileInfo..ctor(String fileName)
   at HsArtExtractor.Util.StringUtils.GetFilenameNoExt(String filename) in H:\Pr
ojects\Hearthstone\Lab\ArtExtractor\HsArtExtractor\Util\StringUtils.cs:line 58
   at HsArtExtractor.Hearthstone.CardArt.ArtCard..ctor(String id, CardDef def, M
aterial portrait, Material bar) in H:\Projects\Hearthstone\Lab\ArtExtractor\HsAr
tExtractor\Hearthstone\CardArt\ArtCard.cs:line 33
   at HsArtExtractor.Hearthstone.Bundle.CardsBundle.ProcessObjects() in H:\Proje
cts\Hearthstone\Lab\ArtExtractor\HsArtExtractor\Hearthstone\Bundle\CardsBundle.c
s:line 59
   at HsArtExtractor.Hearthstone.Bundle.CardsBundle..ctor(List`1 bundles) in H:\
Projects\Hearthstone\Lab\ArtExtractor\HsArtExtractor\Hearthstone\Bundle\CardsBun
dle.cs:line 34
   at HsArtExtractor.Hearthstone.CardArtExtractor.LoadCardDefs(String hsDir) in
H:\Projects\Hearthstone\Lab\ArtExtractor\HsArtExtractor\Hearthstone\CardArtExtra
ctor.cs:line 150
   at HsArtExtractor.Hearthstone.CardArtExtractor.Extract(CardArtExtractorOption
s opts) in H:\Projects\Hearthstone\Lab\ArtExtractor\HsArtExtractor\Hearthstone\C
ardArtExtractor.cs:line 71
   at HsArtExtractorCLI.Program.CardArtCommand(CardArtOptions opts)
   at HsArtExtractorCLI.Program.<>c.<Main>b__0_1(CardArtOptions opts)
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,TResult](ParserResul
t`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 n
otParsedFunc)
   at HsArtExtractorCLI.Program.Main(String[] args)

Log File:
[hs-art-extractor.txt](https://github.com/andburn/hs-art-extractor/files/894819/hs-art-extractor.txt)

PS: The Kindly Grandmother card does not have a image associated with it's ID, only the adventure hero appear and can be used in his place (same image).

**Comment by mjschutz** [comment]
Hi again.

I changed HsArtExtractor.Util.GetFilenameNoExt to remove invalid chars from filename string as a temporary solution and it worked (attached file).

```
// To get the filename without the extension, mainly for texture asset path
public static string GetFilenameNoExt(string filename)
{
	if (string.IsNullOrWhiteSpace(filename))
		return null;

	filename = string.Join("", filename.Split(Path.GetInvalidPathChars())); // solution
	FileInfo fi;
	try
	{
		fi = new FileInfo(filename);
	}
	catch
	{
		fi = new FileInfo("C:/" + filename);
	}

	var extIdx = fi.Name.LastIndexOf(fi.Extension);
	return fi.Name.Substring(0, extIdx);
}
```

[StringUtils.txt](https://github.com/andburn/hs-art-extractor/files/895039/StringUtils.txt)

**Comment by andburn** [comment]
Thanks, fixed for now.
